import type { FootballConcept, KnowledgeEdge } from "./types";

/*
  The concept layer of the knowledge graph.

  Every concept is written to be *teachable*: what it is, why it matters, what
  it looks like on the pitch, the cue a player can hold in their head, and how
  it is trained. Studies, sessions and MIDO explanations all draw from here, so
  the same idea is described consistently everywhere in the product.
*/

export const CONCEPTS: FootballConcept[] = [
  // ── attacking movement ────────────────────────────────────
  {
    slug: "dropping-between-lines",
    name: "Dropping between the lines",
    area: "tactical",
    phase: "in-possession",
    definition:
      "A forward or attacking midfielder leaving the last line to receive in the space between the opponent's midfield and defence.",
    why: "It forces a defender into a decision no defender likes: follow and open the space behind, or stay and let you turn.",
    looksLike: [
      "The striker checks away from the centre-back before the pass is played",
      "A centre-back steps out of the back line, leaving a gap for a runner",
      "The receiver takes the ball on the half-turn, already facing forward",
    ],
    cues: ["Move away before you move towards", "Arrive as the ball leaves, not before", "Know your out before you receive"],
    trains: [
      "Rondo with a floating receiver who must receive between two lines of players",
      "Pattern play: CB to dropping CF, layoff, third-man run in behind",
      "Small-sided game where a goal counts double if it starts with a pass between the lines",
    ],
    positions: ["CF", "AM", "CM"],
  },
  {
    slug: "blindside-movement",
    name: "Blindside movement",
    area: "tactical",
    phase: "in-possession",
    definition:
      "Positioning yourself outside a defender's field of vision so that they must choose between watching the ball and watching you.",
    why: "A defender who cannot see you cannot react to you. Separation is created before the sprint starts, not during it.",
    looksLike: [
      "The forward drifts behind the shoulder of the far centre-back as a cross develops",
      "A late run arriving from outside the defender's head-turn",
      "The attacker holds still until the defender turns their head to the ball",
    ],
    cues: ["If they can see you and the ball, you are too early", "Live behind the shoulder", "Move on their head-turn"],
    trains: [
      "Crossing drill with a passive defender who must track a blindside runner",
      "Two-attacker box movement: one pins, one arrives blindside",
      "Film study of your own clips, marking every moment you were in the defender's vision",
    ],
    positions: ["CF", "W", "AM"],
  },
  {
    slug: "runs-in-behind",
    name: "Running in behind",
    area: "tactical",
    phase: "in-possession",
    definition: "Attacking the space behind the defensive line, timed to the moment the passer can play it.",
    why: "It is the run that either scores or pushes the defensive line back, which creates the space everyone else plays in.",
    looksLike: [
      "The run starts as the passer's head comes up, not before",
      "A curved run that stays onside and opens the body to goal",
      "Repeated runs even when the pass does not come — the line still drops",
    ],
    cues: ["Time it to their touch", "Curve to stay on", "Run to be wrong nine times"],
    trains: ["Timing drill against a mannequin offside line", "Pattern: switch, then run in behind the far side", "Repeated-sprint conditioning shaped like real runs"],
    positions: ["CF", "W", "AM"],
  },
  {
    slug: "occupying-the-last-line",
    name: "Occupying the last line",
    area: "tactical",
    phase: "in-possession",
    definition: "Holding a position on the shoulder of the deepest defender to pin the defensive line deep.",
    why: "Pinning defenders is a gift to your teammates: every metre the line stays back is a metre of space between the lines.",
    looksLike: ["The striker stays high while midfielders receive in front", "Two defenders occupied by one forward", "The forward resists dropping into congested space"],
    cues: ["Pin first, then move", "Hold the line, do not drift to the ball", "Your stillness is a service"],
    trains: ["Positional game with a target player who may not leave the top zone", "Structured 11v11 with zone restrictions"],
    positions: ["CF", "W"],
  },
  {
    slug: "third-man-runs",
    name: "Third-man runs",
    area: "tactical",
    phase: "in-possession",
    definition: "A pattern where A passes to B, and C — who was not involved in the first pass — arrives to receive B's layoff.",
    why: "The defence reacts to the ball; the third man is the player they are not watching. It is the cleanest way to break a compact block.",
    looksLike: ["Pass into the striker, layoff, midfielder running past to receive", "The runner starting before the layoff is made", "One-touch layoff to keep the defence facing the wrong way"],
    cues: ["Start your run on the first pass", "One touch for the layoff", "The third man is always the free man"],
    trains: ["Three-player patterns into a finish", "Rondos where only a third-man combination counts as an escape", "Conditioned game: goals from third-man combinations count double"],
    positions: ["CF", "AM", "CM", "W"],
  },
  {
    slug: "creating-separation",
    name: "Creating separation",
    area: "technical",
    phase: "in-possession",
    definition: "Making a yard of space from a marker with movement, body position or a change of pace before the ball arrives.",
    why: "Almost every attacking action is decided before the touch. Separation is the difference between receiving and being tackled.",
    looksLike: ["A hard step towards the ball, then away", "Physical contact used to feel where the defender is", "A change of speed rather than a change of direction"],
    cues: ["Two speeds beat one", "Feel them, then leave them", "Sell the first move"],
    trains: ["1v1 receiving under contact with a live defender", "Check-away-and-receive circuits", "Back-to-goal work against a marker allowed to touch"],
    positions: ["CF", "W", "AM"],
  },

  // ── receiving and technique ───────────────────────────────
  {
    slug: "scanning",
    name: "Scanning",
    area: "mental",
    phase: "all",
    definition: "Checking your shoulders before the ball arrives so you already know the picture when you receive.",
    why: "Elite players do not think faster — they gather information earlier. The decision is made before the touch, not after it.",
    looksLike: ["Two or more head-turns while the ball travels to the passer", "A final scan as the ball leaves the passer's foot", "The first touch going into space that was checked, not guessed"],
    cues: ["One look as it travels, one as it leaves", "Scan for pressure, then for the out", "Know your next pass before you receive"],
    trains: ["Rondo with a coloured-bib call behind the receiver", "Number-call drills while receiving", "Film review counting scans per reception"],
    positions: ["GK", "CB", "FB", "DM", "CM", "AM", "W", "CF"],
  },
  {
    slug: "receiving-half-turn",
    name: "Receiving on the half-turn",
    area: "technical",
    phase: "in-possession",
    definition: "Opening your body as the ball arrives so a single touch takes you from facing your own goal to facing forward.",
    why: "It converts a backwards situation into a forwards one without spending a touch — the difference between recycling and progressing.",
    looksLike: ["Back foot open before the ball arrives", "The first touch travelling away from pressure", "Head up immediately after the touch"],
    cues: ["Open the back foot early", "Touch into the space you checked", "Receive facing the game"],
    trains: ["Y-shaped passing patterns with a mandatory half-turn", "Pressure receiving with a defender behind", "Rondo with a rule that forward-facing receptions score"],
    positions: ["DM", "CM", "AM", "CF"],
  },
  {
    slug: "first-touch-under-pressure",
    name: "First touch under pressure",
    area: "technical",
    phase: "in-possession",
    definition: "Controlling the ball into a usable position while a defender is closing, rather than simply stopping it.",
    why: "A good first touch is a pass to yourself. A bad one turns possession into a defensive action.",
    looksLike: ["The touch travelling into space, not under the feet", "The body between defender and ball as the touch is taken", "A touch that already sets the next action"],
    cues: ["Touch is a pass to yourself", "Away from pressure, into space", "Soften and travel"],
    trains: ["Receiving circuits with a chasing defender", "Wall-pass work with a directional first touch", "Small-sided games with a two-touch maximum"],
    positions: ["CB", "FB", "DM", "CM", "AM", "W", "CF"],
  },
  {
    slug: "near-post-finishing",
    name: "Near-post finishing",
    area: "technical",
    phase: "in-possession",
    definition: "Attacking the front zone of the six-yard box and finishing early, before the defence and keeper can set.",
    why: "The near post is a decision made before the cross is struck. Hesitate and the space is gone.",
    looksLike: ["The attacker arriving in front of the defender, not behind", "A redirected finish rather than a struck one", "Contact made in front of the near post, across the keeper"],
    cues: ["Decide before the cross", "Attack in front", "Contact, not power"],
    trains: ["Repetition finishing from cut-back and driven crosses", "One-touch redirection work at speed", "Conditioned game where near-post finishes count double"],
    positions: ["CF", "W"],
  },
  {
    slug: "hold-up-play",
    name: "Hold-up play",
    area: "technical",
    phase: "in-possession",
    definition: "Receiving with a defender behind you and keeping the ball long enough for the team to advance.",
    why: "It is how a team escapes its own half without a 60-metre pass, and how a forward turns pressure into territory.",
    looksLike: ["Arm across the defender to feel and hold", "A cushioned first touch away from contact", "A layoff into a supporting runner rather than a hopeful turn"],
    cues: ["Feel them before the ball arrives", "Big body, small touch", "Layoff, then spin"],
    trains: ["Back-to-goal work with a live defender and a supporting midfielder", "Long-ball receiving under contact", "Conditioned games with a mandatory forward target"],
    positions: ["CF"],
  },

  // ── defending and out of possession ───────────────────────
  {
    slug: "pressing-triggers",
    name: "Pressing triggers",
    area: "tactical",
    phase: "out-of-possession",
    definition: "The specific cues — a heavy touch, a backwards pass, an open body — that tell the team to press now, together.",
    why: "Pressing is not effort, it is timing. Pressing on the wrong cue leaves the team stretched and passed through.",
    looksLike: ["Press starting on a defender's poor first touch", "The whole line stepping together on a backward pass", "A curved press that shuts the inside pass"],
    cues: ["Press the touch, not the pass", "Curve to lock the inside", "Go together or not at all"],
    trains: ["Pressing patterns against a build-up shape", "Conditioned game where winning the ball high scores double", "Film study identifying the trigger frame by frame"],
    positions: ["CF", "W", "AM", "CM", "DM", "FB", "CB"],
  },
  {
    slug: "counter-pressing",
    name: "Counter-pressing",
    area: "tactical",
    phase: "transition",
    definition: "Attempting to win the ball back immediately in the seconds after losing it, while the opponent is still disorganised.",
    why: "The moment after a turnover is the moment the opponent is least organised — and the moment your own shape is closest to their ball.",
    looksLike: ["Two or three players converging on the ball within seconds", "The nearest player delaying while others close the passing lanes", "Recovery runs aimed at passing options rather than the ball"],
    cues: ["First five seconds", "Nearest presses, next closes the lane", "Lose it, win it back"],
    trains: ["Transition games with a five-second counter-press rule", "Small-sided games with immediate restart on turnover"],
    positions: ["CF", "W", "AM", "CM", "DM"],
  },
  {
    slug: "defending-the-inside",
    name: "Defending the inside channel",
    area: "tactical",
    phase: "out-of-possession",
    definition: "Approaching an opponent from an angle that shuts the pass or dribble into the middle, forcing play outside.",
    why: "Goals come from central areas. Sending a player down the line is a win; letting them come inside is a problem for the whole team.",
    looksLike: ["The defender's body angled to show the opponent wide", "A press curved from the inside out", "A full-back holding the inside shoulder of a winger"],
    cues: ["Show them the line", "Inside shoulder first", "Approach on an angle, never straight"],
    trains: ["1v1 defending with a channel restriction", "Pressing patterns from the front line backwards"],
    positions: ["FB", "CB", "W", "DM", "CM"],
  },
  {
    slug: "rest-defence",
    name: "Rest defence",
    area: "tactical",
    phase: "in-possession",
    definition: "The shape a team holds while attacking, designed to deal with the counter-attack before it happens.",
    why: "Most goals conceded by good teams start in their own attack. Rest defence is how a team attacks without being reckless.",
    looksLike: ["Two centre-backs and a pivot staying behind the ball", "Full-backs staggered rather than both high", "The counter-press covered by players already positioned"],
    cues: ["Attack with a plan for losing it", "Stagger, do not level", "Cover the counter before it starts"],
    trains: ["Attacking patterns with a transition-goal condition for the defending team", "Positional play with mandatory rest-defence roles"],
    positions: ["CB", "FB", "DM", "CM"],
  },
  {
    slug: "compact-block",
    name: "The compact block",
    area: "tactical",
    phase: "out-of-possession",
    definition: "A deliberately narrow, short defensive shape that denies the central space and invites play into wide areas.",
    why: "Space is the opponent's raw material. A block that removes central space removes most of their good options.",
    looksLike: ["Roughly 25-30 metres between the highest and deepest defender", "Midfield line shifting as a unit with the ball", "Wide players tucking in until the ball goes wide"],
    cues: ["Distances before duels", "Shift together, arrive together", "Give the outside, keep the inside"],
    trains: ["Shape work with a rope or connected units", "11v11 with the block restricted to a zone"],
    positions: ["CB", "FB", "DM", "CM", "W"],
  },
  {
    slug: "offside-line",
    name: "Playing the offside line",
    area: "tactical",
    phase: "out-of-possession",
    definition: "A defensive line stepping up together at the moment the pass is struck, so runners are caught offside.",
    why: "It compresses the pitch and turns the opponent's best runs into free-kicks for you — but only if the line moves as one.",
    looksLike: ["The back line stepping on the passer's plant foot", "One defender calling and the others reacting instantly", "The line holding rather than dropping when the ball is under pressure"],
    cues: ["Step on the strike", "One voice", "Hold when the ball is pressured"],
    trains: ["Back-four unit work with a stepping cue", "Defensive line drills with live runners"],
    positions: ["CB", "FB"],
  },

  // ── build-up and structure ────────────────────────────────
  {
    slug: "positional-play",
    name: "Positional play",
    area: "tactical",
    phase: "in-possession",
    definition:
      "Organising players across the pitch so that occupied zones create constant passing triangles, width and depth, whoever the individuals are.",
    why: "It makes good decisions likely rather than heroic. Structure produces the free man; the free man produces progression.",
    looksLike: ["Five players across the last line, width held by the widest players", "Never two players in the same vertical lane", "Constant triangles around the ball"],
    cues: ["Occupy the zone, not the ball", "Width holds, inside plays", "Find the free man"],
    trains: ["Positional games on a zoned pitch", "Build-up patterns from goal-kicks", "Rondos with positional restrictions"],
    positions: ["GK", "CB", "FB", "DM", "CM", "AM", "W", "CF"],
  },
  {
    slug: "half-spaces",
    name: "Half-spaces",
    area: "tactical",
    phase: "in-possession",
    definition: "The two vertical lanes between the centre of the pitch and the touchlines, where a player can face both the goal and the wing.",
    why: "It is the most valuable receiving area in the modern game: close enough to goal to threaten, wide enough to be uncomfortable to mark.",
    looksLike: ["An attacking midfielder receiving between full-back and centre-back", "Cut-backs from the half-space rather than the touchline", "Wingers holding width so the half-space stays open"],
    cues: ["Between their full-back and centre-back", "Face the goal and the wing", "Wide holds so inside opens"],
    trains: ["Zoned positional games rewarding half-space receptions", "Pattern play finishing from half-space cut-backs"],
    positions: ["AM", "CM", "W", "CF"],
  },
  {
    slug: "build-up-3-2",
    name: "The 3-2 build-up",
    area: "tactical",
    phase: "in-possession",
    definition: "Building with three defenders and two midfielders in front of them, creating a stable base against a two- or three-player press.",
    why: "It guarantees numerical superiority in the first line and covers the counter-attack at the same time — structure and rest defence in one shape.",
    looksLike: ["A full-back stepping into midfield beside the pivot", "Three at the back against two pressers", "Goalkeeper included as a passing option to make it four against two"],
    cues: ["Superiority in the first line", "Two in front, always", "Invite the press, then break it"],
    trains: ["Goal-kick build-up patterns against a live press", "Positional games starting from the keeper"],
    positions: ["GK", "CB", "FB", "DM", "CM"],
  },
  {
    slug: "switch-of-play",
    name: "Switching play",
    area: "tactical",
    phase: "in-possession",
    definition: "Moving the ball quickly from one side of the pitch to the other to attack the space the opponent's shift has vacated.",
    why: "A block that shifts is a block that leaves a far side. The switch is how you punish organised defending.",
    looksLike: ["Two or three passes travelling across the pitch faster than the block can shift", "The far winger already isolated 1v1 when the ball arrives", "The switch played before the pressure arrives, not after"],
    cues: ["Attract, then switch", "Far side stays wide", "Switch early, not late"],
    trains: ["Positional games with a mandatory switch before scoring", "Long-passing accuracy circuits under pressure"],
    positions: ["CB", "DM", "CM", "AM", "W"],
  },
  {
    slug: "overload-to-isolate",
    name: "Overload to isolate",
    area: "tactical",
    phase: "in-possession",
    definition: "Deliberately crowding one side of the pitch to drag the defence across, then switching to a one-against-one on the far side.",
    why: "It manufactures the situation your best dribbler wants, on purpose, instead of hoping for it.",
    looksLike: ["Four players combining in one corner while the far winger stays wide", "A switch arriving to an isolated attacker with grass in front", "The far full-back left alone against your best 1v1 player"],
    cues: ["Crowd one side, free the other", "Stay wide even when the ball is far", "Overload to isolate, then attack"],
    trains: ["Positional games with a locked far-side 1v1 zone", "Pattern play from overload to switch to cross"],
    positions: ["W", "AM", "CM", "FB"],
  },

  // ── mental and physical ───────────────────────────────────
  {
    slug: "decision-speed",
    name: "Decision speed",
    area: "mental",
    phase: "all",
    definition: "The time between recognising a picture and acting on it — shortened by preparation, not by rushing.",
    why: "At every level up, the time on the ball shrinks. Players do not survive by moving faster; they survive by deciding earlier.",
    looksLike: ["Pre-decided actions executed the instant the ball arrives", "Fewer touches in congested areas", "Calm actions in situations that look chaotic"],
    cues: ["Decide before you receive", "Pick the option, then take the touch", "Simple early beats brilliant late"],
    trains: ["Constrained small-sided games with touch limits", "Scanning drills with decision calls", "Video review of your own delayed decisions"],
    positions: ["GK", "CB", "FB", "DM", "CM", "AM", "W", "CF"],
  },
  {
    slug: "repeat-sprint-ability",
    name: "Repeat sprint ability",
    area: "physical",
    phase: "all",
    definition: "The capacity to produce near-maximal sprints repeatedly with incomplete recovery, as matches actually demand.",
    why: "One sprint is a test result. Fifteen sprints in ninety minutes is a football quality — and it is the one that decides late goals.",
    looksLike: ["The tenth run in behind as sharp as the first", "Recovery runs still made at speed in the last twenty minutes", "Sprint output holding across both halves"],
    cues: ["Train the tenth rep, not the first", "Quality over volume", "Recover between, not during"],
    trains: ["Repeated-sprint protocols with football-shaped distances", "High-intensity interval blocks", "Aerobic base work to speed recovery between efforts"],
    positions: ["CF", "W", "FB", "CM", "AM"],
  },
  {
    slug: "acceleration",
    name: "Acceleration",
    area: "physical",
    phase: "all",
    definition: "The ability to reach high speed in the first five to ten metres, where almost all football separation happens.",
    why: "Football is rarely won at top speed. It is won in the first three steps, when a defender is still deciding.",
    looksLike: ["Winning the first two steps of a duel", "Getting to a loose ball first from a standing start", "Separation created before the defender turns"],
    cues: ["First three steps", "Push the ground away", "Low and long out of the first step"],
    trains: ["Short sprint work from varied starting positions", "Resisted sprints and sled work", "Strength work targeting force production"],
    positions: ["CF", "W", "FB", "CB", "AM"],
  },
];

/** Typed, directional relationships between nodes. */
export const CONCEPT_EDGES: KnowledgeEdge[] = [
  { from: "dropping-between-lines", to: "scanning", kind: "requires", note: "You cannot receive between lines without knowing what is behind you." },
  { from: "dropping-between-lines", to: "receiving-half-turn", kind: "requires" },
  { from: "dropping-between-lines", to: "creating-separation", kind: "requires" },
  { from: "dropping-between-lines", to: "compact-block", kind: "counters", note: "Dropping drags a defender out of a compact block, or opens space behind them." },
  { from: "blindside-movement", to: "creating-separation", kind: "partOf" },
  { from: "blindside-movement", to: "offside-line", kind: "counters" },
  { from: "runs-in-behind", to: "acceleration", kind: "requires" },
  { from: "runs-in-behind", to: "offside-line", kind: "counters" },
  { from: "runs-in-behind", to: "repeat-sprint-ability", kind: "requires" },
  { from: "occupying-the-last-line", to: "half-spaces", kind: "relatesTo", note: "Pinning the last line keeps the space between the lines available." },
  { from: "third-man-runs", to: "compact-block", kind: "counters" },
  { from: "third-man-runs", to: "hold-up-play", kind: "requires" },
  { from: "near-post-finishing", to: "decision-speed", kind: "requires" },
  { from: "near-post-finishing", to: "blindside-movement", kind: "requires" },
  { from: "hold-up-play", to: "first-touch-under-pressure", kind: "requires" },
  { from: "receiving-half-turn", to: "scanning", kind: "requires" },
  { from: "first-touch-under-pressure", to: "scanning", kind: "requires" },
  { from: "pressing-triggers", to: "positional-play", kind: "counters", note: "A well-timed press attacks the moment a positional structure is least stable." },
  { from: "counter-pressing", to: "rest-defence", kind: "requires" },
  { from: "counter-pressing", to: "pressing-triggers", kind: "relatesTo" },
  { from: "compact-block", to: "half-spaces", kind: "counters" },
  { from: "positional-play", to: "half-spaces", kind: "partOf" },
  { from: "positional-play", to: "rest-defence", kind: "partOf" },
  { from: "positional-play", to: "build-up-3-2", kind: "partOf" },
  { from: "build-up-3-2", to: "pressing-triggers", kind: "counters" },
  { from: "switch-of-play", to: "compact-block", kind: "counters" },
  { from: "overload-to-isolate", to: "switch-of-play", kind: "requires" },
  { from: "half-spaces", to: "scanning", kind: "requires" },
  { from: "decision-speed", to: "scanning", kind: "requires" },
  { from: "defending-the-inside", to: "compact-block", kind: "partOf" },
  { from: "offside-line", to: "compact-block", kind: "partOf" },
  { from: "acceleration", to: "repeat-sprint-ability", kind: "relatesTo" },
];

const BY_SLUG = new Map(CONCEPTS.map((c) => [c.slug, c]));

export function concept(slug: string): FootballConcept | null {
  return BY_SLUG.get(slug) ?? null;
}

export function conceptsBySlugs(slugs: string[]): FootballConcept[] {
  return slugs.map((s) => BY_SLUG.get(s)).filter((c): c is FootballConcept => Boolean(c));
}
