import Link from "next/link";
import { Dumbbell } from "lucide-react";

/*
  The last edge of the loop.

  Film Room links a concept into training. A study links itself into training.
  The Capture extension links a saved lesson into training. The development
  priority — the thing every one of those paths converges on — had no link at
  all, even though `goal:` has been a valid session focus in
  `sanitizeBrief` and `validSourceKeys` the whole time. The engine was
  waiting; nothing ever called it.

  It is a link rather than a button because it hands off to the existing
  training surface, which already knows how to draft, show the proposal and
  wait for the player to accept it. Nothing is generated by arriving here, and
  nothing is written until the player says so — the same contract the rest of
  MIDO keeps.
*/

export function BuildNextWork({
  goalId,
  evidenceCount,
}: {
  goalId: string;
  /** How much of the record this session will be built from. */
  evidenceCount: number;
}) {
  return (
    <div>
      <Link
        href={`/app/training?focus=${encodeURIComponent(`goal:${goalId}`)}`}
        className="flex h-9 items-center gap-2 rounded-lg bg-signal px-3.5 text-sm font-medium text-white transition-colors hover:bg-signal-deep"
      >
        <Dumbbell className="size-3.5" />
        Build my next work
      </Link>
      <p className="mt-2 text-[11px] leading-relaxed text-text-faint">
        {evidenceCount > 0
          ? `MIDO drafts a session around this priority and the ${evidenceCount} ${
              evidenceCount === 1 ? "moment" : "moments"
            } behind it. You see it before anything is saved.`
          : "MIDO drafts a session around this priority. You see it before anything is saved."}
      </p>
    </div>
  );
}
